### ISSUE TITLE
Epistemic and aletoric uncertainty for a given instance

### ISSUE THREAD

**Issue by federicocau** [Moffran/calibrated_explanations#30]
Hey devs, is it possible to print/return the aleatoric and epistemic uncertainty/confidence for a given instance?

I saw a function called "get_confidence()" in the CalibratedExplanations class but apparently is not working.

**Comment by tuvelofstrom** [comment]
Hi Federico
Sorry for not responding sooner! 

You can access the epistemic and aletoric uncertainty from individual explanation objects through the `prediction` attribute. `prediction` is a dictionary with the `predict`, `low`, `high`, and `classes` fields (for classification). `predict` contains the calibrated predict proba (i.e., the epistemic uncertainty) for the positive class (in binary classification) or for the class label assigned to `classes` (for multi-class). `low` and `high` contain the lower and upper bound of the Venn-Abers predictions (i.e., the aleotirc uncertainty) for the same value as is represented in `predict` (class 1 for binary and the class assigned to `classes` for multi-class).

```python
...
ce = CalibratedExplainer(model, calX, calY)
factual_explanations = ce.explain_factual(testX)

factual_explanation0 = factual_explanations.get_explanation(0)

calibrated_predict_proba = factual_explanation0.prediction['predict'] 
calibrated_uncertainty_interval = [factual_explanation0.prediction['low'], factual_explanation0.prediction['high']]
```

The `get_confidence` method only return the difference between the lower and upper percentiles in `low_high_percentiles`, used for regression. 

Adding methods for easy access to these values (as well as the feature weights, accessible trough `feature_weights` and `feature_predict` at the same level as `prediction`) should obviously have been included from start.

**Comment by federicocau** [comment]
Hi tuvelofstrom, thank you for the clarification! All clear now :D

**Comment by tuvelofstrom** [comment]
Two different actions will be taken as response to this issue:
* [x] Add a demo notebook illustrating how to work with the data composing the explanations for:
  - [x] Binary classification
  - [ ] Multi-class classification
  - [ ] Regression
* [ ] Adding functions to the `CalibratedExplanations` collection class and the `FactualExplanation` and `CounterfactualExplanation` classes to access the information easily.

**Comment by tuvelofstrom** [comment]
With [v0.4.0](https://github.com/Moffran/calibrated_explanations/releases/tag/v0.4.0), all explanations have a `__repr__` which can be referred to as an example on how to access the rule details. Adding a description, for documentation purposes, of the internal structure used to build an explanation remains to be done.
